---
# Implement ansibleuser
- name: Implement ansibleuser
  hosts: all
  become: yes

  tasks:
  - name: Add a new user ansibleuser
    user:
      name: ansibleuser
      shell: /bin/bash
      group: wheel
      append: yes

  - name: Set authorized keys from controller machine
    authorized_key:
      user: ansibleuser
      state: present
      key: "{{ lookup('file', '/home/ansibleuser/.ssh/id_rsa.pub') }}"

  - name: Add user "ansibleuser" to sudo
    lineinfile:
      path: /etc/sudoers.d/ansibleuser
      line: 'ansibleuser ALL=(ALL) NOPASSWD: ALL'
      state: present
      mode: 0440
      create: yes
      validate: '/usr/sbin/visudo -cf %s'

  - name: Set includedir in sudoers
    lineinfile:
      dest: /etc/sudoers
      line: "#includedir /etc/sudoers.d"
      state: present
      validate: "/usr/sbin/visudo -cf %s"

# Install Apache
- name: Install Apache
  hosts: web
  become: yes

  tasks:
  - name: "Installing Apache"
    yum:
      name: httpd
      state: latest

  - name: "Set firewall" 
    firewalld:
        port: 80/tcp
        permanent: yes
        state: enabled

  - name: "reload service firewalld, in all cases"
    systemd:
      name: firewalld
      state: reloaded
    
  - name: "Start Apache"
    command: sudo systemctl start httpd

# Install NodeJs
- name: Install NodeJs
  hosts: app
  become: yes

  tasks:
  - name: "Install NodeJs Step 1."
    shell: curl -sL https://rpm.nodesource.com/setup_10.x | sudo -E bash -
    
  - name: "Install NodeJs Step 2."
    yum:
      name:
        - gcc-c++
        - make
        - nodejs
        - git
      state: latest

  - name: Install required npm package(s)
    npm:
      name: supervisor
      global: yes

  - name: Implement nodejs code from git
    git:
      repo: https://github.com/ch-e-mistry/DevOps_Training.git
      dest: /nodejs/
      force: yes

  - name: Copy prepared unit file
    copy:
      src: ./nodejsapp.service
      dest: /usr/lib/systemd/system/nodejsapp.service
      owner: root
      group: root
      mode: '0644'
