---
- name: Implement ansibleuser
  hosts: all
  become: yes

  tasks:
  - name: Add a new user ansibleuser
    user:
      name: ansibleuser
      shell: /bin/bash
      group: wheel
      append: yes

  - name: Set authorized keys from controller machine
    authorized_key:
      user: ansibleuser
      state: present
      key: "{{ lookup('file', '/home/ansibleuser/.ssh/id_rsa.pub') }}"

  - name: Add user "ansibleuser" to sudo
    lineinfile:
      path: /etc/sudoers.d/ansibleuser
      line: 'ansibleuser ALL=(ALL) NOPASSWD: ALL'
      state: present
      mode: 0440
      create: yes
      validate: '/usr/sbin/visudo -cf %s'

  - name: Set includedir in sudoers
    lineinfile:
      dest: /etc/sudoers
      line: "#includedir /etc/sudoers.d"
      state: present
      validate: "/usr/sbin/visudo -cf %s"

- name: Install Apache
  hosts: web
  become: yes